第3回課題
ruizapp/RaiseTech pull request #5
Opened 2023-06-29 06:58 UTC by ruizapp

2023-06-29 07:10 UTC, MasatoshiMizumoto requested changes
コメント入れてますのでご確認ください！
https://github.com/ruizapp/RaiseTech/pull/5/files

2023-06-29 07:10 UTC, MasatoshiMizumoto commented on lecture02.md
これ消えてしまいますけど良いんでしたっけ？

2023-06-29 07:18 UTC, ruizapp commented on lecture02.md
問題ないです！

2023-06-30 04:27 UTC, MasatoshiMizumoto commented on lecture02.md
全課題の報告は最後転職のポートフォリオに使うので、無くなると困るのではと思うのですが、本当に問題ないですかね？？

2023-06-30 09:46 UTC, ruizapp commented on lecture02.md
修正いたしました。
確認お願い致します。

2023-07-01 02:28 UTC, MasatoshiMizumoto approved these changes
LGTM!
お疲れさまでした！

2023-07-01 05:05 UTC, merged